// <auto-generated />
using System;
using Exam_My_Example.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exam_My_Example.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    [Migration("20220107211743_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exam_My_Example.Database.Models.Document1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateVizdorovlenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnoz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jalobi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naznachenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Spravochnik1Id")
                        .HasColumnType("int");

                    b.Property<int>("Spravochnik2Id")
                        .HasColumnType("int");

                    b.Property<int>("TypePriema")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Spravochnik1Id");

                    b.HasIndex("Spravochnik2Id");

                    b.ToTable("Document1s");
                });

            modelBuilder.Entity("Exam_My_Example.Database.Models.Spravochnik1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Spravochnik1s");
                });

            modelBuilder.Entity("Exam_My_Example.Database.Models.Spravochnik2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doljnost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otdelenie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spravochnik2s");
                });

            modelBuilder.Entity("Exam_My_Example.Database.Models.Document1", b =>
                {
                    b.HasOne("Exam_My_Example.Database.Models.Spravochnik1", "spravochnik1")
                        .WithMany()
                        .HasForeignKey("Spravochnik1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam_My_Example.Database.Models.Spravochnik2", "spravochnik2")
                        .WithMany()
                        .HasForeignKey("Spravochnik2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
